Repository opencast-ilias/OpenCast, pull requests merged in 2024-06, with the labels that each got.

#299 [Release 8] Upgrade OC-PHP-LIB (v1.7)
  composer.json
  composer.lock
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/elan-ev/opencast-api/CHANGELOG.md
  vendor/elan-ev/opencast-api/README.md
  vendor/elan-ev/opencast-api/composer.json
  vendor/elan-ev/opencast-api/src/OpencastApi/Opencast.php
  vendor/elan-ev/opencast-api/src/OpencastApi/Rest/OcIngest.php
  vendor/elan-ev/opencast-api/src/OpencastApi/Rest/OcPlaylistsApi.php
  vendor/elan-ev/opencast-api/src/OpencastApi/Rest/OcRestClient.php
  vendor/elan-ev/opencast-api/src/OpencastApi/Rest/OcSearch.php
  vendor/elan-ev/opencast-api/tests/DataProvider/PlaylistsDataProvider.php
  vendor/elan-ev/opencast-api/tests/DataProvider/SearchDataProvider.php
  vendor/elan-ev/opencast-api/tests/DataProvider/SetupDataProvider.php
  vendor/elan-ev/opencast-api/tests/Unit/OcIngestTest.php
  vendor/elan-ev/opencast-api/tests/Unit/OcSearchTest.php
  vendor/elan-ev/opencast-api/tests/UnitMock/OcSearchTestMock.php
Labels: enhancement, dependencies, Priority: High, ILIAS 8

#300 [Release 7] Upgrade OC-PHP-LIB (v1.7)
  composer.json
  composer.lock
  vendor/composer/installed.json
  vendor/composer/installed.php
  vendor/elan-ev/opencast-api/CHANGELOG.md
  vendor/elan-ev/opencast-api/README.md
  vendor/elan-ev/opencast-api/composer.json
  vendor/elan-ev/opencast-api/src/OpencastApi/Opencast.php
  vendor/elan-ev/opencast-api/src/OpencastApi/Rest/OcIngest.php
  vendor/elan-ev/opencast-api/src/OpencastApi/Rest/OcPlaylistsApi.php
  vendor/elan-ev/opencast-api/src/OpencastApi/Rest/OcRestClient.php
  vendor/elan-ev/opencast-api/src/OpencastApi/Rest/OcSearch.php
  vendor/elan-ev/opencast-api/tests/DataProvider/PlaylistsDataProvider.php
  vendor/elan-ev/opencast-api/tests/DataProvider/SearchDataProvider.php
  vendor/elan-ev/opencast-api/tests/DataProvider/SetupDataProvider.php
  vendor/elan-ev/opencast-api/tests/Unit/OcIngestTest.php
  vendor/elan-ev/opencast-api/tests/Unit/OcSearchTest.php
  vendor/elan-ev/opencast-api/tests/UnitMock/OcSearchTestMock.php
Labels: enhancement, dependencies, Priority: Medium, ILIAS 7

#288 [Release 8] fix livestream playback issues by removing hlsConfig options
  js/opencast/src/Paella/config/config.json
Labels: ILIAS 8

#295 [Release 8] Paella improvements
  classes/Conf/class.xoctConfGUI.php
  classes/Player/class.xoctPlayerGUI.php
  js/opencast/dist/index.js
  js/opencast/src/Paella/config/config.json
  js/opencast/src/Paella/package-lock.json
  js/opencast/src/Paella/package.json
  js/opencast/src/Paella/paella-player.min.js
  js/opencast/src/Paella/player.js
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/Model/Config/PluginConfig.php
  src/UI/PaellaConfig/PaellaConfigFormBuilder.php
  src/Util/Player/StandardPlayerDataBuilder.php
Labels: bug, enhancement, dependencies, Priority: High, ILIAS 8

#287 fix livestream playback issues by removing hlsConfig options
  js/opencast/src/Paella/config/config.json
Labels: ILIAS 7

#296 [Release 7] Paella improvements
  classes/Conf/class.xoctConfGUI.php
  classes/Player/class.xoctPlayerGUI.php
  js/opencast/dist/index.js
  js/opencast/src/Paella/config/config.json
  js/opencast/src/Paella/package-lock.json
  js/opencast/src/Paella/package.json
  js/opencast/src/Paella/paella-player.min.js
  js/opencast/src/Paella/player.js
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/Model/Config/PluginConfig.php
  src/UI/PaellaConfig/PaellaConfigFormBuilder.php
  src/Util/Player/StandardPlayerDataBuilder.php
Labels: bug, enhancement, dependencies, Priority: High, ILIAS 7

#285 [FIX] make code compliant to the ILIAS 7 version
  classes/trait.ilObjShowDuplicates.php
Labels: ILIAS 8
