Repository opencast-ilias/OpenCast, pull requests merged in 2024-08, with the labels that each got.

#306 [Release 8] Linked Series Listing in different places
  classes/Event/class.xoctEventGUI.php
  classes/Series/class.xoctSeriesGUI.php
  classes/class.ilObjOpenCastGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  templates/default/tpl.links_list.html
  templates/default/tpl.links_list_item.html
Labels: enhancement, ILIAS 8, Ready to merge

#308 [Release 8] Update title with uploaded file name
  js/opencast/dist/index.js
  js/opencast/src/UI/FileInputMutationObserver.js
  js/opencast/src/index.js
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/UI/EventFormBuilder.php
  src/UI/Metadata/MDFormItemBuilder.php
Labels: enhancement, ILIAS 8, Ready to merge

#309 [Release 8] Avoid starting workflow when event is in ingesting or pending state
  classes/Event/class.xoctEventRenderer.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  src/Model/Event/Event.php
Labels: bug, ILIAS 8, Ready to merge

#322 [Release 8] Avoid unnecessary ACL update when updating series metadata
  classes/Series/class.xoctSeriesGUI.php
Labels: bug, ILIAS 8, Ready to merge

#332 Fix for cli installation v8.1.x
  classes/class.ilOpenCastPlugin.php
Labels: bug, ILIAS 8, Ready to merge

#331 Update readme to add CLI update info
  README.md
Labels: enhancement, Priority: High, Ready to merge

#307 [Release 7] Linked Series Listing in different places
  classes/Event/class.xoctEventGUI.php
  classes/Series/class.xoctSeriesGUI.php
  classes/class.ilObjOpenCastGUI.php
  lang/ilias_de.lang
  lang/ilias_en.lang
  templates/default/tpl.links_list.html
  templates/default/tpl.links_list_item.html
Labels: enhancement, ILIAS 7, Ready to merge

#318 [Release 8] Scheduling Parser throws error on null inputs
  src/Model/Scheduling/SchedulingParser.php
Labels: bug, ILIAS 8

#320 [Release 8] String to int cast in PublicationUsage
  src/Model/Publication/Config/PublicationUsageGroup.php
Labels: bug

#304 [Release 8] disable restorePlaybackRate feature for livestreams
  CHANGELOG.md
  plugin.php
Labels: Ready to merge

#314 [Release 8] Fix ID of new Events missing
  classes/Service/class.xoctEventAPI.php
Labels: bug, enhancement, ILIAS 8, Ready to merge

#316 [Release 8] Date Handling in xoctEventAPI
  classes/Service/class.xoctEventAPI.php
Labels: Ready to merge

#303 [Release 7] disable restorePlaybackRate feature for livestreams
  js/opencast/src/Paella/default_theme/opencast_live_theme.json
Labels: Ready to merge

#347 [FIX] wrong translation of scheduled events
  lang/ilias_de.lang
  lang/ilias_en.lang
Labels: ILIAS 8
